### ISSUE TITLE
Unexpected token "{"

### ISSUE THREAD

**Issue by Oelin** [shapesecurity/unminify#23]
I ran unminify on this valid JavaScript file: https://pastebin.com/raw/88pnXgpd, and it threw the following error:

```
throw this.createUnexpected(this.lookahead);
      ^

Error: [1:108]: Unexpected token "{"
    at new JsError (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/tokenizer.js:165:104)
    at GenericParser.createError (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/tokenizer.js:296:14)
    at GenericParser.createUnexpected (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/tokenizer.js:275:23)
    at GenericParser.expect (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:185:18)
    at GenericParser.parseCatchClause (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1008:12)
    at GenericParser.parseTryStatement (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:962:32)
    at GenericParser.parseStatementHelper (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:610:23)
    at GenericParser.isolateCoverGrammar (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1084:23)
    at GenericParser.parseStatement (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:574:23)
    at GenericParser.parseStatementListItem (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:567:23)
    at GenericParser.parseBody (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:305:61)
    at GenericParser.parseFunctionBody (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:279:44)
    at GenericParser.parseArrowExpressionTail (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1155:21)
    at GenericParser.parseAssignmentExpressionOrTarget (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1184:21)
    at GenericParser.isolateCoverGrammar (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1084:23)
    at GenericParser.parseAssignmentExpression (/usr/local/lib/node_modules/unminify/node_modules/shift-parser/dist/parser.js:1167:19)
```

I'm not sure if I'm doing something wrong, but this seems like a bug.

**Comment by Oelin** [comment]
Node 10.24 parses the file correctly.
